export default {

    METATAGS_CHANGE: 'METATAGS_CHANGE',

    NOTIFIER_RESET: 'NOTIFIER_RESET',
    NOTIFIER_SUCCESS: 'NOTIFIER_SUCCESS',
    NOTIFIER_INFO: 'NOTIFIER_INFO',
    NOTIFIER_ERROR: 'NOTIFIER_ERROR',

    USER_LOGIN_INIT: 'USER_LOGIN_INIT',
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
    USER_LOGOUT: 'USER_LOGOUT',
    LOGIN_SET_DATA: 'LOGIN_SET_DATA',
    INIT_LOGIN_MODE: 'INIT_LOGIN_MODE',
    USER_RESET_PASSWORD_REQUEST: 'USER_RESET_PASSWORD_REQUEST',
    USER_RESET_PASSWORD_REQUEST_ERROR: 'USER_RESET_PASSWORD_REQUEST_ERROR',
    USER_RESET_PASSWORD_REQUEST_SUCCESS: 'USER_RESET_PASSWORD_REQUEST_SUCCESS',

    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_PASSWORD_RESET_DATA: 'RESET_PASSWORD_RESET_DATA',

    LOGIN_AUTHENTICATE_FACEBOOK : 'LOGIN_AUTHENTICATE_FACEBOOK',
    LOGIN_AUTHENTICATE_FACEBOOK_SUCCESS : 'LOGIN_AUTHENTICATE_FACEBOOK_SUCCESS',
    LOGIN_AUTHENTICATE_FACEBOOK_ERROR : 'LOGIN_AUTHENTICATE_FACEBOOK_ERROR',

    LOGIN_REGISTRATION_FACEBOOK: 'LOGIN_REGISTRATION_FACEBOOK',
    LOGIN_REGISTRATION_FACEBOOK_SUCCESS: 'LOGIN_REGISTRATION_FACEBOOK_SUCCESS',
    LOGIN_REGISTRATION_FACEBOOK_ERROR:  'LOGIN_REGISTRATION_FACEBOOK_ERROR',

    USER_REGISTRATION: 'USER_REGISTRATION',
    USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
    USER_REGISTRATION_ERROR: 'USER_REGISTRATION_ERROR'

}
